<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Cucumber" time="2.296" tests="1" skipped="0" failures="1" errors="0">
<testcase classname="Class 2 module" name="Check if admin able to update a Class with a deleted classID in the endpoint" time="0.188">
<failure type="java.lang.AssertionError" message="expected [404] but found [200]">
<![CDATA[java.lang.AssertionError: expected [404] but found [200]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at generics.ApiUtils.validateStatusCode(ApiUtils.java:27)
	at stepDefinitions.class2Steps.admin_receives_status_for_updateClass(class2Steps.java:397)
	at âœ½.Admin receives 404 "Not Found" Status for updateClass(file:///Users/mathumathibalakrishnan/eclipse/Mathumathi_2024/Team2_ChangeMakers_RestAssured/src/test/resources/features/class2.feature:177)
]]>
</failure>
<system-out><![CDATA[
Given Admin sets Authorization for class module.............................passed
When Admin creates PUT Request and sends HTTPS Request with deleted classId for updateClass.passed
Then Admin receives 404 "Not Found" Status for updateClass..................failed
]]></system-out>
</testcase>
</testsuite>
